<?php
/**
 * StringInsecureDeserializationJsonDetectionTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * securityapi
 *
 * The security APIs help you detect and block security threats.
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.3.1
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * StringInsecureDeserializationJsonDetectionTest Class Doc Comment
 *
 * @category    Class */
// * @description Result of performing an Insecure Deserialization JSON protection operation
/**
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class StringInsecureDeserializationJsonDetectionTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "StringInsecureDeserializationJsonDetection"
     */
    public function testStringInsecureDeserializationJsonDetection()
    {
    }

    /**
     * Test attribute "successful"
     */
    public function testPropertySuccessful()
    {
    }

    /**
     * Test attribute "contained_json_insecure_deserialization_attack"
     */
    public function testPropertyContainedJsonInsecureDeserializationAttack()
    {
    }

    /**
     * Test attribute "original_input"
     */
    public function testPropertyOriginalInput()
    {
    }
}
