<?php
/**
 * UrlSsrfThreatDetectionResponseFullTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * securityapi
 *
 * The security APIs help you detect and block security threats.
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.3.1
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * UrlSsrfThreatDetectionResponseFullTest Class Doc Comment
 *
 * @category    Class */
// * @description Result of checking a URL for SSRF threats
/**
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class UrlSsrfThreatDetectionResponseFullTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "UrlSsrfThreatDetectionResponseFull"
     */
    public function testUrlSsrfThreatDetectionResponseFull()
    {
    }

    /**
     * Test attribute "clean_url"
     */
    public function testPropertyCleanUrl()
    {
    }

    /**
     * Test attribute "threat_level"
     */
    public function testPropertyThreatLevel()
    {
    }
}
