<?php
/**
 * ContentThreatDetectionApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * securityapi
 *
 * The security APIs help you detect and block security threats.
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.3.1
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use \Swagger\Client\Configuration;
use \Swagger\Client\ApiException;
use \Swagger\Client\ObjectSerializer;

/**
 * ContentThreatDetectionApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class ContentThreatDetectionApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for contentThreatDetectionAutomaticThreatDetectionString
     *
     * Automatically detect threats in an input string.
     *
     */
    public function testContentThreatDetectionAutomaticThreatDetectionString()
    {
    }

    /**
     * Test case for contentThreatDetectionCheckSqlInjectionString
     *
     * Check text input for SQL Injection (SQLI) attacks.
     *
     */
    public function testContentThreatDetectionCheckSqlInjectionString()
    {
    }

    /**
     * Test case for contentThreatDetectionCheckXxe
     *
     * Protect text input from XML External Entity (XXE) attacks.
     *
     */
    public function testContentThreatDetectionCheckXxe()
    {
    }

    /**
     * Test case for contentThreatDetectionDetectInsecureDeserializationJsonString
     *
     * Detect Insecure Deserialization JSON (JID) attacks in a string.
     *
     */
    public function testContentThreatDetectionDetectInsecureDeserializationJsonString()
    {
    }

    /**
     * Test case for contentThreatDetectionProtectXss
     *
     * Protect text input from Cross-Site-Scripting (XSS) attacks through normalization.
     *
     */
    public function testContentThreatDetectionProtectXss()
    {
    }
}
