<?php
/**
 * NetworkThreatDetectionApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * securityapi
 *
 * The security APIs help you detect and block security threats.
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.3.1
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use \Swagger\Client\Configuration;
use \Swagger\Client\ApiException;
use \Swagger\Client\ObjectSerializer;

/**
 * NetworkThreatDetectionApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class NetworkThreatDetectionApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for networkThreatDetectionDetectSsrfUrl
     *
     * Check a URL for Server-side Request Forgery (SSRF) threats.
     *
     */
    public function testNetworkThreatDetectionDetectSsrfUrl()
    {
    }

    /**
     * Test case for networkThreatDetectionIsBot
     *
     * Check if IP address is a Bot client threat.
     *
     */
    public function testNetworkThreatDetectionIsBot()
    {
    }

    /**
     * Test case for networkThreatDetectionIsThreat
     *
     * Check if IP address is a known threat.
     *
     */
    public function testNetworkThreatDetectionIsThreat()
    {
    }

    /**
     * Test case for networkThreatDetectionIsTorNode
     *
     * Check if IP address is a Tor node server.
     *
     */
    public function testNetworkThreatDetectionIsTorNode()
    {
    }
}
